
services:
  app:
    platform: linux/amd64
    build:
      context: .
      dockerfile: Dockerfile
    image: backend-retta
    container_name: app-retta
    ports:
      - "8000:8000"
    volumes:
      - .:/var/www
    depends_on:
      - db
    networks:
      - laravel
      
  db:
    image: mysql:8.0
    container_name: retta-db
    restart: always
    environment:
      MYSQL_DATABASE: retta
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - laravel

  queue:
    image: backend-retta
    container_name: queue-retta
    command: php artisan queue:work
    restart: unless-stopped
    volumes:
      - .:/var/www
    depends_on:
      - db
    networks:
      - laravel

networks:
  laravel:
    driver: bridge

volumes:
  db_data: